# Generated by Django 4.1 on 2022-08-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_todolist_checked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todolist',
        ),
    ]
