# Generated by Django 4.1 on 2022-08-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_delete_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=30)),
                ('taskDesc', models.TextField()),
                ('checked', models.BooleanField()),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
