# Generated by Django 4.1 on 2022-08-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
