# Generated by Django 4.1 on 2022-08-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_todolist_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='sname',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
